name: Manual Plugin Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to deploy'
        required: true
        type: choice
        options:
          - main
          - dev

env:
  PROD_MOODLE_ROOT: /var/www/html/moodle
  DEV_MOODLE_ROOT: /var/www/html/moodle

jobs:
  package-plugin:
    name: Package Plugin
    runs-on: ubuntu-latest
    outputs:
      zip-file: ${{ steps.zip.outputs.zip-file }}
      timestamp: ${{ steps.timestamp.outputs.time }}
      plugin-directory: ${{ steps.plugin-dir.outputs.plugin-directory }}
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Paths Filter
        uses: dorny/paths-filter@v3
        id: filter-plugin-changes
        with:
          list-files: json
          filters: |
            plugin-changes:
              - 'mod/**'

      - name: Determine plugin directory
        id: plugin-dir
        run: |
          FILES='${{ toJSON(steps.filter-plugin-changes.outputs.plugin-changes_files) }}'
          PLUGIN_DIR=$(echo "$FILES" | jq -r '.[0]' | cut -d'/' -f2)
          echo "plugin-directory=$PLUGIN_DIR" >> $GITHUB_OUTPUT

      - name: Generate timestamp
        id: timestamp
        run: echo "time=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create deployment package
        id: zip
        run: |
          if [ "${{ steps.filter-plugin-changes.outputs.plugin-changes }}" != "true" ]; then
            echo "No plugin changes detected. Skipping zip creation."
            exit 0
          fi
          
          ZIP_FILE="${{ github.event.inputs.branch }}-${{ steps.plugin-dir.outputs.plugin-directory }}-${{ steps.timestamp.outputs.time }}.zip"
          cd mod
          zip -qr "../$ZIP_FILE" "${{ steps.plugin-dir.outputs.plugin-directory }}"
          echo "zip-file=$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-package-${{ github.event.inputs.branch }}
          path: ${{ steps.zip.outputs.zip-file }}
          retention-days: 5

  deploy:
    name: Deploy to Instance
    needs: package-plugin
    runs-on: 
      - self-hosted
      - Linux
      - X64
      - ${{ github.event.inputs.branch == 'dev' && 'dev' || 'prod' }}
    if: contains(fromJson('["dev", "main"]'), github.event.inputs.branch)
    environment:
      name: ${{ github.event.inputs.branch == 'main' && 'production' || 'development' }}
      url: ${{ github.event.inputs.branch == 'main' && 'http://moodle-lb-244874513.us-east-2.elb.amazonaws.com' || 'http://moodle-dev-lb-244874513.us-east-2.elb.amazonaws.com' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-package-${{ github.event.inputs.branch }}
          path: /tmp

      - name: Determine Moodle Root Path
        id: determine-path
        run: |
          case "${{ github.event.inputs.branch }}" in
            dev)  MOODLE_PATH=${{ env.DEV_MOODLE_ROOT }} ;;
            main) MOODLE_PATH=${{ env.PROD_MOODLE_ROOT }} ;;
          esac
          echo "MOODLE_PATH=$MOODLE_PATH" >> $GITHUB_ENV

      - name: Compare version numbers
        run: |
          PLUGIN_DIR="${{ needs.package-plugin.outputs.plugin-directory }}"
          TEMP_ARTIFACT_DIR="/tmp/temp_artifact_${{ needs.package-plugin.outputs.timestamp }}"
          mkdir -p "$TEMP_ARTIFACT_DIR"

          unzip -q "/tmp/${{ needs.package-plugin.outputs.zip-file }}" -d "$TEMP_ARTIFACT_DIR"

          artifact_file="$TEMP_ARTIFACT_DIR/$PLUGIN_DIR/version.php"
          server_file="${{ env.MOODLE_PATH }}/mod/$PLUGIN_DIR/version.php"

          if [ ! -f "$artifact_file" ]; then
            echo "::error:: Artifact version file not found!"
            exit 1
          fi

          ver_artifact=$(grep '\$plugin->version' "$artifact_file" | awk -F'=' '{print $2}' | tr -d " ;")
          echo "Artifact version: $ver_artifact"

          if [ -f "$server_file" ]; then
            ver_server=$(grep '\$plugin->version' "$server_file" | awk -F'=' '{print $2}' | tr -d " ;")
            echo "Server version: $ver_server"

            if [ "$ver_server" -gt "$ver_artifact" ]; then
              echo "::error:: Server version ($ver_server) is greater than artifact version ($ver_artifact). Deployment aborted."
              exit 1
            fi
          else
            echo "Server version file not found, proceeding."
          fi

          rm -rf "$TEMP_ARTIFACT_DIR"

      - name: Backup current plugin directory
        run: |
          PLUGIN_DIR="${{ needs.package-plugin.outputs.plugin-directory }}"
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          PLUGIN_DIR_PATH="${{ env.MOODLE_PATH }}/mod/$PLUGIN_DIR"
          BACKUP_FILE="/tmp/$PLUGIN_DIR-backup-${TIMESTAMP}.zip"

          if [ -d "$PLUGIN_DIR_PATH" ]; then
            sudo zip -r "$BACKUP_FILE" "$PLUGIN_DIR_PATH"
            echo "Backup created at $BACKUP_FILE"
          else
            echo "No existing plugin directory found, skipping backup."
          fi

      - name: Deploy to Moodle
        run: |
          PLUGIN_DIR="${{ needs.package-plugin.outputs.plugin-directory }}"
          DEPLOY_DIR="${{ env.MOODLE_PATH }}/mod"
          sudo unzip -qo "/tmp/${{ needs.package-plugin.outputs.zip-file }}" -d "$DEPLOY_DIR"
          sudo chown -R www-data:www-data "$DEPLOY_DIR/$PLUGIN_DIR"